name: boot_camp
channels:
  - conda-forge
  - apple
dependencies:
  - python=3.9
  - pandas
  - tensorflow
  - scikit-learn
  - numpy
  - requests
  - pillow
  - sentence-transformers
  - ipykernel
  - transformers
  - tf-keras
  - pip
  - pip:
    - gradio
